# Generated by Django 5.0.3 on 2024-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0003_sneakers_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
