# Generated by Django 5.0.3 on 2024-04-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
