# Generated by Django 5.0.3 on 2024-04-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_sneakers_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
